version: '3'
services:
  db:
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lost-pet-finder-db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
